# Variables
APP=whiteboxDES

#Special rules and targets
.PHONY: all clean help LtablesGen

#Rules and targets

all: $(APP)

$(APP):
	@cd src && $(MAKE)
	@cp -f src/$(APP) .

LtablesGen:
	@cd src && $(MAKE) LtablesGen
	@cp -f src/LtablesGen .

clean:
	@cd src && $(MAKE) clean
	@rm -f $(APP) LtablesGen


help :
	@echo -e "Usage :"
	@echo -e "  make all		build the software"
	@echo -e "  make LtablesGen	build the lookup tables generator"
	@echo -e "  make clean		remove all files generated by make"
	@echo -e "  make help		display this help"
